### ISSUE TITLE
semver compatible version number

### ISSUE THREAD

**Issue by aguegu** [TIDC/ssml-document#2]
The version of this repo is interesting. 

The current installed version in my package.json is `1.0.5592`. And I believe the version with #1 closed is version `1.0.57` or `1.0.571`. 

I know they are newer than `1.0.5592`, at https://www.npmjs.com/package/ssml-document?activeTab=versions

But [ncu](https://www.npmjs.com/package/npm-check-updates) does not work in this way. And [npm version](https://docs.npmjs.com/cli/v8/commands/npm-version) command does not manage version naming in this way. So these new releases would not show up in `ncu -u`. People may miss your new releases. 

And in default `package.json`, it was `"ssml-document": "^1.0.5592"`

I am afraid that `1.0.57` is not `^` `1.0.5592`. 

Please consider it.

**Comment by Vinlic** [comment]
感谢你的指正，这说明我们的版本号命名比较混乱，后续将谨慎考虑版本号命名 :D
